language: python

python:
  - '3.4'

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pep8

before_install:
  - pip install -U coveralls pip pytest pytest-cov setuptools wheel tox

script: tox

after_success:
  - coveralls

notifications:
  slack:
    secure: CuyuO7xWmWebhRw64LJzl/ab1wiQbpmDgm0ui8/M5Yg3J9Oz1m7R/0kSBbcDwA2oerQCpEEVh6yB6okyFJ+0HSC08SepI0W68/AwbvIDxYOtLgCBeLLZoelWyDXVh1E45pK+kLoFh5dhRF1oQDxMMXE0q7V8jKQggrPw1amRdTMrBv6AXIWgyvS8T7oHOgABnxgzsEsBevXUSbjbyfKL2TwOt897A2CTGj0nUsvb3nviGG6eOwp0dGSBsAMU9MwUWkCWD1P2KehwDleXQG8QnkI30oNiBK8c72JwCQ0V5Ays62ZvkcA3B/bBK0UQOlqL73Oa80JPbgAcz0QYnzgCiNuvLxoYARnBEzvO4wqlzJWG2xPF9BjCvfslbgF758YSP8GD84DjXLDYw39HDEDMgeW2uooC5441S74OTYzkQXs42flNs/eF4O1HSWFUUdGMM1bBQ2+gBPnJFdCsoExEth+yLEqzRGx9XwcQQWMuk5qiomySOk/MKgGcK/wDCUPsRhRR6GFZdiyD8y666PKFiMNjp8FyotP9kGf05dG4bQrKZQUyf2KTb770eHJmOCqwFed7UVf/GYU/gTZYo0nUTWw6x168K/Z/W/4PzHtTHTuoQ9oGU86B1hrGtVLvE/RQBYf8yzBM9m1yhhO8H4qqLWUNFpcBlclQhIDjTaFH+K4=

before_deploy:
  - python setup.py build sdist bdist_wheel
  - if [ "x" == "$(grep $(git tag -l --points-at=HEAD) setup.py)x" ]; then echo 'new tag does not exist in setup.py; bailing!'; exit 1; else echo "tag found in setup.py"; fi

deploy:
  - provider: pypi
    user: atal
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    password:
      secure: "ULhamG0pbq34MzobLc97xvwJzzQZ7uTUe8t7wgrpKEQU/aqAmlBg3QL8SkPg94ov+n+QWvO4StIl0Z/SESyhsw/R2O9/ugBHHM/63c0p/ewAsnXAs6MPhs2/cntvVVuYQmm6gP/MpIPSnBNmJzF9RTkP5HVIEkTBlzwYgPmFW2jaC9AbfQVQnEmmfs9S1Fs6wvGJ5D/WDaGltpezlPPg4ziPrTdNt/vb1PmWvrJ/B8TFNLkrrcXO0js2x7QSWkHtw+TeYsZRj/EYjP+6J+BxTrIRPp43QsSigN/Rb4zgKd1oEire6yyFio2Io4kRDhWkOvogmFL2RQVYx5PnuC95zcdlAFg5V+s859p+dJxZzGEeIJBlOMj+q+nSMkgwjGYyT+khIXjXSw7k1Kc40AjDJXrjlq+YYyGjlPBH18g1i/yPfHx0mjkLH0w1Nm+7luuy1R3/tETGVRJ+fsIjS6r0ZwHlbEHokBHJFisPwBhL/klFafKumRTLBtmeRrF6xS33RILYBoMiqM5cL8dwIy4AOMpMQsSAjLRtAfcIt2x+baJTUW8SC1jZsJM13UJCrpUnxdMJVa+d1jUc/wO2M0ujmb9Yom+y/Iw4BXbGeeVdIDo8Sto2Q54JzBy9juNqObqX8Z6qhug0WfUG3nMD7CDGBNKvph3MSVeGPXBGqBz5c+M="
    on:
      tags: true
      repo: ccpgames/pypicloud-tools
      condition: $TOXENV = py34
  - provider: releases
    api_key:
      secure: "uWikcUAwK5f0lj77rO5b87dXCFGHRpT8/yG9t9sOJuodYMrpbROMRzMyjwQmp1eNjXiNypEPW6rwtr+wWbtjNEUyn9P8/F9qj3rsLfAW7D9dMIrD6hzZ2qMPs7Gn3EF44lqsXlsctqtKqElUDheU4yJM7mKOpkLCv9KaWmawuu7yGEbi92Lb4aNjQCU8cu1l3OtQix0fMbk/BVAMR2P/7vH/toDuL1el7PtPjbkv6tjS5HeSoPlt9upUHiHIjQ/fnwtcEcMTX6zSnslMpVbXD2LvdU/mLDjFNR+EC8dvNaRLG/YqsUCJgHbuIQnk1ZKDv52ldmiGk6zqaI/Mp6pRiPMrnFozwbZfkuo5QtVpSE1yAwZxy8HbQaDz1wZJhv61X0BPw88vVxuWcG9y2Pvf3jntCZWKTI/J1mkv9Rb2+EVKi6oc0NI5tArN7hDpMEWRS+NI8EfOBHiCAPJLDTQO6LLZhNEXQikrTri+MmQgN42P4KIAwrENlFI1k1RqL8X052cN8pgCDHJ41Rw/fjZgWlnJVdn3XkYx+loSTCSkmZJ1cTB1QxQuux6wNq8j6Q/qVcALV2QeH9ZqKGTnVqknpiZLmoXHwL6dpKJ9pL5nvkEu7FSFX4XbKc1XGf3Jcgf5t34Gz/zu3YMiAziuooFQPeEi/v4vZfNDqslOeP+wqXU="
    file: "/home/travis/build/ccpgames/pypicloud-tools/dist/*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py34
